server:
  port: 8885

spring:
  application:
    name: monitor-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        ip: 127.0.0.1
      config:
        server-addr: 127.0.0.1:8848
        import-check:
          enabled: false


feign:
  hystrix:
    enabled: true


