server:
  port: 8882

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://你的配置仓库地址
          search-paths: config-repo
          username: 你的git用户名
          password: 你的git密码
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        ip: 127.0.0.1
      config:
        server-addr: 127.0.0.1:8848
        import-check:
          enabled: false
feign:
  hystrix:
    enabled: true

